### ISSUE TITLE
The first time I open the program on win10, I get an error

### ISSUE THREAD

**Issue by sxchen-med** [CarlGao4/ClassIn-Replay-Download#1]
显示”由于找不到 MSVCP140 ATOMIC WAIT.dll，无法继续执行代码。重新安装程序可能会解决此问题。“，重新下载也没能解决

**Comment by CarlGao4** [comment]
[msvcp140_atomic_wait.zip](https://github.com/CarlGao4/ClassIn-Replay-Download/files/11645405/msvcp140_atomic_wait.zip)

Extract this file and place it in the same folder of the program

**Comment by sxchen-med** [comment]
It worked. Thanks.
