### ISSUE TITLE
无法下载“课程"分类下的视频

### ISSUE THREAD

**Issue by moliqing2023** [CarlGao4/ClassIn-Replay-Download#4]
无法下载“课程"分类下的视频，也有其他人有类似的问题，求优化完善，非常感谢！
![Snipaste_2023-09-08_23-14-16](https://github.com/CarlGao4/ClassIn-Replay-Download/assets/60815177/0f41a1fb-20cf-4927-84e1-349949a58fa7)
![Snipaste_2023-09-08_23-18-00](https://github.com/CarlGao4/ClassIn-Replay-Download/assets/60815177/0a3c25fa-26bc-4fc3-8859-9397ebfd60e3)

**Comment by CarlGao4** [comment]
我没有用到过这个视频，请问能提供一个账号我用于测试吗？私信gaoweiqicarl1@163.com联系

**Comment by moliqing2023** [comment]
已经发送

**Comment by CarlGao4** [comment]
请尝试一下最新的1.0.1有没有解决扫描不到视频的问题？

**Comment by moliqing2023** [comment]
ok完美解决，非常感谢！！
