### ISSUE TITLE
Not an available Win32 application under Windows 7

### ISSUE THREAD

**Issue by louiesun** [CarlGao4/ClassIn-Replay-Download#6]
this may be one of the solutions: 
[solve?](https://blog.csdn.net/guo_lei_lamant/article/details/79047744)

**Comment by CarlGao4** [comment]
![image](https://github.com/CarlGao4/ClassIn-Replay-Download/assets/57826826/50f6b460-f354-4e9a-bdc0-5cb9f869b2b0)
