### ISSUE TITLE
I received 70 error messages when opening "ClassIn_Replay_Download.cpp" in Visual Studio 2022

### ISSUE THREAD

**Issue by A-l-Y457** [CarlGao4/ClassIn-Replay-Download#7]
I'm sorry to disturb you,but I received 70 error messages when opening "ClassIn_Replay_Download.cpp" in Visual Studio 2022.Also,could you please explain what's the meaning of"please manually add `../include` to your `include` folder. "?（Please forgive my ignorance and poor English.
.）

**Comment by CarlGao4** [comment]
Did you just open the cpp file? You should open the sln file

**Comment by A-l-Y457** [comment]
But the compiler can't find `libavutil/timestamp.h` and I don't know what to do.

**Comment by CarlGao4** [comment]
Right-click on the project, select properties:
![image](https://github.com/CarlGao4/ClassIn-Replay-Download/assets/57826826/e28f9d78-b1c8-4441-9138-f9ab13fe31c5)
And append `../include` to the include directory:
![image](https://github.com/CarlGao4/ClassIn-Replay-Download/assets/57826826/77eb2a23-7525-4290-9cdd-1cb61cbe9531)
